baseurl = "https://hoeunghia-pat.github.io"
title = "Code The Future"
theme = "hugo-theme-cleanwhite"
languageCode = "vi"
paginate = 10 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/header.jpg"
  title = "NLP@UIT"
  slogan = "Research for the better life"
  SEOTitle = "NguyenNghia-PAT"
  keyword = "C++, Qt, Python, Pytorch, Deep learning, Machine learning, AI, Data science, Data visualization"
 
  # Sidebar settings
  sidebar_about_description = "Data Scientist, C++ Developer, Python Developer"
  sidebar_avatar = "images/avatar.jpeg"
  about_me = true

  featured_tags = false 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = false
  email          = "19520178@gm.uit.edu.vn"
  Facebook       = "https://www.facebook.com/hieunghia.nhn"
  github         = "https://github.com/hieunghia-pat"
  # medium         = "https://medium.com/@RichYoungkin"
  # stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  # reddit         = "https://www.reddit.com/user/elevation5280"